// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzC0AlbW0Je_xQUSUemeiNu-gFQ63E_sc',
    appId: '1:345320936259:web:0fc3b4cedc44be1649d5f6',
    messagingSenderId: '345320936259',
    projectId: 'kim-4245c',
    authDomain: 'kim-4245c.firebaseapp.com',
    storageBucket: 'kim-4245c.appspot.com',
    measurementId: 'G-4WKEM18RVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCATcI5zt78lvoOUhkQ3HtvcArC6Krfb8U',
    appId: '1:345320936259:android:d2931675db829a4a49d5f6',
    messagingSenderId: '345320936259',
    projectId: 'kim-4245c',
    storageBucket: 'kim-4245c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpBbbhzN0QtI-mfGSfVpf7PzPCI_7uTLw',
    appId: '1:345320936259:ios:8790997ce8c9a5d749d5f6',
    messagingSenderId: '345320936259',
    projectId: 'kim-4245c',
    storageBucket: 'kim-4245c.appspot.com',
    iosClientId: '345320936259-ej1jbqm9up6ausvl6cer04hi4t4ogeg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.k2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpBbbhzN0QtI-mfGSfVpf7PzPCI_7uTLw',
    appId: '1:345320936259:ios:8790997ce8c9a5d749d5f6',
    messagingSenderId: '345320936259',
    projectId: 'kim-4245c',
    storageBucket: 'kim-4245c.appspot.com',
    iosClientId: '345320936259-ej1jbqm9up6ausvl6cer04hi4t4ogeg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.k2',
  );
}
